import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Body from "./Body";
import Navbar from "./Navbar";

const Home: NextPage = () => {
  return (
    <div className="wrapper min-h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <Body />
      
    </div>
  );
};

export default Home;
